apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
    name: load
spec:
    forProvider:
        name: "123"
        projectId: "45"
        region: Mansoura
        securityGroupRefs:
            - name: sec4
    providerConfigRef:
        name: aws-provider70-credentials-ref
