apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
    name: "11111"
spec:
    forProvider:
        name: test200
        region: eu-centeral-3
        securityGroupRefs:
            - name: sec23
    providerConfigRef:
        name: aws-provider70-credentials-ref
