apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
    name: "2132"
spec:
    forProvider:
        name: test2
        region: eu-centeral-3
        securityGroupRefs:
            - name: sec2
            - name: sec
    providerConfigRef:
        name: aws-provider70-credentials-ref
