apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
    name: load
spec:
    forProvider:
        name: test
        region: eu-centeral-1
        securityGroupRefs:
            - name: sec
            - name: sec2
    providerConfigRef:
        name: aws-provider70-credentials-ref
